[workspace]
members = ["backend-rust", "backend-rust-derive", "backend-rust-derive-lib", "tucant-language-server", "out-dir-include", "tucant-language-server-derive-internal", "tucant-language-server-derive-output", "debug-adapter-protocol-macro-impl", "debug-adapter-protocol"]

[patch.crates-io]
diesel = { git = "https://github.com/diesel-rs/diesel.git" }

[profile.dev]
split-debuginfo = "unpacked"