# SPDX-FileCopyrightText: The tucant Contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

[package]
name = "tucant"
version = "0.1.0"
edition = "2021"
authors = [ "Moritz Hedtke <Moritz.Hedtke@t-online.de>" ]
description = "Test"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11", features = ["cookies"] }
tokio = { version = "1", features = ["fs"] }
html5ever = "0.26"
scraper = "0.13"
futures = "0.3"
diesel = { version = "2", features = ["postgres", "chrono"] }
diesel-async = { version = "0.1", features = ["postgres", "deadpool"] }
dotenvy = "0.15"
anyhow = { version = "1", features = ["backtrace"] }
actix-web = "4"
futures-util = "0.3"
actix-cors = "0.6"
serde = { version = "1", features = ["derive"] }
actix-session = { version = "0.7", features = ["cookie-session"] }
serde_json = "1"
async-stream = { git = "https://github.com/SabrinaJewson/async-stream.rs", branch = "no-proc-macro" }
chrono = { version = "0.4", features = ["serde"] }
deadpool = "0.9"
url = "2"
log = "0.4"
env_logger = "0.9"
derive_more = "0.99"
itertools = "0.10"
diesel_full_text_search = { git = "https://github.com/mohe2015/diesel_full_text_search.git", branch = "mohe2015-patch-1" }
base64 = "0.13"
tucant_derive = { path = "../backend-rust-derive" }
file-lock = "2.1.6"

[patch.crates-io]
diesel = { git = "https://github.com/mohe2015/diesel.git", branch = "add-c-char-type" }